# Rollout: When we first create the deployment a rollout is created and when we do the changes and than create a applcation again 
#a second rollout is created
#Deployment strategy
#1) Recreate:- destroy all of them at once
#2) Rolling update : -destroy and create one by one so there is no downtime (its is default strategy)
#commands:
#kubectl create -f  deployment.yaml
#kubectl get deployment
#kubectl apply -f deployment.yaml
#kubectl set image deployment/myapp-deployment nginx=nginx:1.9.1
#kubectl rollout status deployment/my-app-deploymet
#kubectl rollout history deployment/my-app-deployment
# To rollback kubectl rollout undo deployment/myapp-deployment



apiVersion: v1
kind: Pod
metadata:
  name: myapp-deploment
  labels:
    app: myapp
    type: front-end
spec:
  template:
    metadata:
      name: myapp-pod
      labels:
        app: myapp
        type: front-end
    spec:
     containers:
     - name: nginx-container
       image: nginx-container
  replicas: 3
  selector:
    matchLabels:
      type: front-end